Fix error output when key not found, backticks
Replace backticks with single quotes so main process doesn't end up
running `aws configure` in a subshell and hang waiting for it to exit

diff --git a/src/bin/aws-rotate-iam-keys b/src/bin/aws-rotate-iam-keys
--- a/src/bin/aws-rotate-iam-keys
+++ b/src/bin/aws-rotate-iam-keys
@@ -113,6 +113,6 @@ if [[ "$CURRENT_KEY_ID" != "" ]]; then
     exit 1
   fi
 else
-  echo "Could not find current key. Please ensure you have a profile set up using `aws configure`." >&2
+  echo "Could not find current key. Please ensure you have a profile set up using 'aws configure'." >&2
   exit 1
 fi
