Verify existing credentials before creating key
Check that profiles exist and credentials work before attempting to
create a new key. This makes it easier to debug failures, especially
taking into account that errexit already has been set for the script.

diff --git a/src/bin/aws-rotate-iam-keys b/src/bin/aws-rotate-iam-keys
--- a/src/bin/aws-rotate-iam-keys
+++ b/src/bin/aws-rotate-iam-keys
@@ -84,35 +84,45 @@ FIRST_PROFILE=${PROFILES_ARR[0]}
 
 echo "Rotating iam keys for $PROFILES..."
 
-echo "Verifying existing access key"
-CURRENT_KEY_ID=$(aws iam list-access-keys --output json --profile $FIRST_PROFILE | jq -r '.AccessKeyMetadata[0].AccessKeyId' || exit 1)
-
-if [[ "$CURRENT_KEY_ID" != "" ]]; then
-  echo "Creating new access key"
-  RESPONSE=$(aws iam create-access-key --output json --profile $FIRST_PROFILE | jq .AccessKey)
-  ACCESS_KEY=$(echo $RESPONSE | jq -r '.AccessKeyId')
-  SECRET=$(echo $RESPONSE | jq -r '.SecretAccessKey')
-  if [[ "$ACCESS_KEY" != "" && "$SECRET" != "" ]]; then
-    echo "Created new key $ACCESS_KEY"
-
-    echo "Deleting old access key"
-    aws iam delete-access-key --access-key-id $CURRENT_KEY_ID --profile ${PROFILES_ARR[0]}
-
-    # Rotate the keys in the credentials file for all profiles
-    for i in "${!PROFILES_ARR[@]}"
-    do
-        echo "Updating profile: ${PROFILES_ARR[i]}"
-        aws configure set aws_access_key_id $ACCESS_KEY --profile ${PROFILES_ARR[i]}
-        aws configure set aws_secret_access_key $SECRET --profile ${PROFILES_ARR[i]}
-    done
-
-    echo "Keys rotated"
-    exit 0
-  else
-    echo "Could not create access key. Ensure you only have 1 active access key in your IAM profile." >&2
+echo "Verifying configuration"
+for i in "${!PROFILES_ARR[@]}"
+do
+  ACCESS_KEY_ID=$(aws configure get ${PROFILES_ARR[i]}.aws_access_key_id 2>/dev/null)
+  if [[ -z "$ACCESS_KEY_ID" ]]; then
+    echo "Could not find key for profile ${PROFILES_ARR[i]}. Ensure you have a profile set up using 'aws configure'." >&2
     exit 1
   fi
+  FIRST_KEY_ID=${FIRST_KEY_ID:-$ACCESS_KEY_ID}
+done
+
+echo "Verifying credentials"
+KEY_COUNT=$(aws iam list-access-keys --output json --profile $FIRST_PROFILE | jq '.AccessKeyMetadata | length' || exit 1)
+if [[ "$KEY_COUNT" -gt "1" ]]; then
+  echo "You have more than 1 active access key. Ensure you only have 1 active access key and try again."
+  exit 1
+fi
+
+echo "Creating new access key"
+RESPONSE=$(aws iam create-access-key --output json --profile $FIRST_PROFILE | jq .AccessKey)
+ACCESS_KEY=$(echo $RESPONSE | jq -r '.AccessKeyId')
+SECRET=$(echo $RESPONSE | jq -r '.SecretAccessKey')
+if [[ "$ACCESS_KEY" != "" && "$SECRET" != "" ]]; then
+  echo "Created new key $ACCESS_KEY"
+
+  echo "Deleting old access key"
+  aws iam delete-access-key --access-key-id $FIRST_KEY_ID --profile $FIRST_PROFILE
+
+  # Rotate the keys in the credentials file for all profiles
+  for i in "${!PROFILES_ARR[@]}"
+  do
+      echo "Updating profile: ${PROFILES_ARR[i]}"
+      aws configure set aws_access_key_id $ACCESS_KEY --profile ${PROFILES_ARR[i]}
+      aws configure set aws_secret_access_key $SECRET --profile ${PROFILES_ARR[i]}
+  done
+
+  echo "Keys rotated"
+  exit 0
 else
-  echo "Could not find current key. Please ensure you have a profile set up using 'aws configure'." >&2
+  echo "Failed to create access key. Please correct reported errors and try again." >&2
   exit 1
 fi
